### ISSUE TITLE
can't test locally with nlu "apiai"

### ISSUE THREAD

**Issue by laeshiny** [bothub-studio/support#4]
can't test locally with nlu "apiai"

#### my code
```
response = self.nlu('apiai').ask(event=event)
self.send_message(response.next_message)
```

#### error message
```
bothub test
BotHub> hellow
Traceback (most recent call last):
  File "xxxx/lib/python3.6/site-packages/bothub_cli/lib.py", line 189, in test
    bot.handle_message(event, context)
  File "./bothub/bot.py", line 41, in handle_message
    response = self.nlu('apiai').ask(event=event)
  File "xxxx/lib/python3.6/site-packages/bothub_client/bot.py", line 116, in nlu
    return self.nlu_client_factory.get(vendor)
  File "xxxx/lib/python3.6/site-packages/bothub_client/clients.py", line 269, in get
    return self.NAME_TO_CLIENT.get(vendor)(**self.integrations_params.get(vendor))
  File "xxxx/lib/python3.6/site-packages/bothub_client/clients.py", line 207, in __init__
    apiai_module = __import__('apiai')
ModuleNotFoundError: No module named 'apiai'
```

**Comment by toracle** [comment]
The error message indicates that python couldn't find an `apiai` package.

When I added an api.ai NLU module to SDK, I thought it's not necessary to install apiai package everyone, even who don't use an NLU module. So I didn't add `apiai` as a dependency package. The problem will be resolved when I add `apiai` to bothub sdk as a dependency package.

As a workaround for now, you may install `apiai` package yourself on your localhost, using `pip install apiai` command.

**Comment by laeshiny** [comment]
thanks. It works :)
